// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DragController from "./drag_controller"
application.register("drag", DragController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import LinkController from "./link_controller"
application.register("link", LinkController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ReorderController from "./reorder_controller"
application.register("reorder", ReorderController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import ClickAnalyticsController from "./click_analytics_controller"
application.register("click-analytics", ClickAnalyticsController)
